name: Print Hello
on:
  pull_request:
  push:
    branches:
      - main
      - foobar
    tags:
      - *

jobs:
  print_hello:
    name: "Print Hello"
    runs-on: ubuntu-20.04
    env:
      LIMIT: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.push.ref || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Print Hello
        run: echo "Hello World"

      - name: Print on Push to foobar
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/foobar' }}
        run: echo "Hello on push ${{ github.event.ref }}"


