name: Print Hello
on:
  pull_request:
  push:
    branches:
      - main
      - foobar
jobs:
  print_hello:
    name: "Print Hello"
    runs-on: ubuntu20.04
    steps:
      - name: Print Hello
      run: echo "Hello World"

      - name: Print on Push to foobar
      if: ${{ github.event_name == 'push' }}
      run: echo "Hello on push ${{ github.event.ref }}


