name: Print Hello
on:
  pull_request:
  push:
    branches:
      - main
      - foobar
    tags:
      - f*

jobs:
  print_hello:
    name: "Print Hello"
    runs-on: ubuntu-latest
    env:
      REF_TYPE: ${{ github.ref_type }}
      LIMIT: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha}}
    steps:
      - name: Print Hello
        run: echo "Hello World"

      - name: Print on Push to foobar
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/foobar' }}
        run: echo "Hello on push ${{ github.event.ref }}"

      - name: Install buck
        run: |
          wget -q https://github.com/facebook/buck/releases/download/v2021.05.05.01/buck.2021.05.05.01_all.deb
          sudo apt install ./buck.2022.05.05.01_all.deb


